### ISSUE TITLE
2.x breaking change could have been avoided

### ISSUE THREAD

**Issue by boneskull** [sindresorhus/get-port#1]
Given that `get-port` now returns a `Promise`, code that expects it to accept a callback will obviously not work.  

I'd encourage you to use something like [bluebird's asCallback()](http://bluebirdjs.com/docs/api/ascallback.html).  this will make 1.x code still work against 2.x.

```js
function getPort(callback) {
  return new Promise(resolve, reject) {
    // guts
  })
    .asCallback(callback);
});
```

not a huge issue, but this can cause confusion, because users who used to promisify `get-port` themselves will end up with a non-working function.

**Comment by boneskull** [comment]
(I can send a PR if you like)

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm gonna pass. I'm not interested in having two different interfaces.

If devs upgrade major versions without looking at the changes, they deserve what's coming to them, tbh ;)

**Comment by boneskull** [comment]
> If devs upgrade major versions without looking at the changes, they deserve what's coming to them, tbh ;) 

You're free to have that attitude.

The Promise behavior could have been introduced in a minor when used with a similar solution as above; it wasn't necessary to break anything here.

**Comment by sindresorhus** [comment]
> it wasn't necessary to break anything here.

Promise change wasn't the only breaking change: https://github.com/sindresorhus/get-port/commit/7335d75e8af2c2c48fa324e88d3e4c0144a946c7
