### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by dotchev** [sindresorhus/get-port#14]
It seems there is a chance for race conditions.
In the time between `getPort` and the real use of the port (most probably another listen on the same port) it is possible that another process takes the port and it is no longer free.
At least this should be highlighted in the documentation.

**Comment by sindresorhus** [comment]
I had just assumed that was obvious, but I agree it should be documented.

**Comment by Turbo87** [comment]
@sindresorhus it seems that this issue can be closed now that https://github.com/sindresorhus/get-port/pull/20 was merged.
