### ISSUE TITLE
Default port not catching errors

### ISSUE THREAD

**Issue by reesmanp** [sindresorhus/get-port#16]
I am using the default port feature but it does not seem to be catching the error on node 8.9 if the default port is taken. A `listen EADDRINUSE` error propagates.

**Comment by sindresorhus** [comment]
[This test](https://github.com/sindresorhus/get-port/blob/9782a3450af88eec601360589e73f48c4c9315e8/test.js#L24-L35) is passing in Node.js 8.9. Would you be able to submit a [failing test](https://github.com/avajs/ava#failing-tests)?

**Comment by reesmanp** [comment]
![screen shot 2018-01-11 at 9 37 36 am](https://user-images.githubusercontent.com/5932381/34838513-39a89b76-f6b3-11e7-91a7-728a42efc6ea.png)

I have an instance of my application running on the default port and here I just ran a second instance and it fails when trying the default port.

**Comment by kaihaase-wd** [comment]
@reesmanp I had the same problem and could fix it by handing over both the port and the host in the configuration: 

```
import getPort = require('get-port');
const port = await getPort({ port: 3000, host: '0.0.0.0' });
```

**Comment by reesmanp** [comment]
@kaihaase-wd your solution seems to work. Thanks! 
@sindresorhus I would recommend adding the solution to the docs.
I am closing this issue now.

**Comment by shellscape** [comment]
@kaihaase-wd for whatever reason, I can confirm the same. Adding the host resolved an issue whereby get-port would return a port currently in use.
