### ISSUE TITLE
UDP ports do also exist

### ISSUE THREAD

**Issue by ibc** [sindresorhus/get-port#18]
The author of this module may want to clarify in the README / API that `get-port` is just valid for getting a free **TCP** port.

Yes, this is Node.js and in Node.js all is about HTTP and stuff on top of HTTP. But **UDP** does also exist.

Thanks.

**Comment by shellscape** [comment]
Holy condescending issue, Batman. File a PR if you think the README can use an update. Good grief.

**Comment by ibc** [comment]
No thanks, I try to avoid packages/software that assumes that Internet is TCP. Fortunately there are alternatives.
