### ISSUE TITLE
Array of preferred ports instead of just one number

### ISSUE THREAD

**Issue by AxelTerizaki** [sindresorhus/get-port#19]
I think it could be interesting to have the ability to pass an array of preferred ports instead of just one before get-port gives up and tries a random port.

Would this be possible?

**Comment by kevva** [comment]
I have the same question as in https://github.com/sindresorhus/get-port/issues/6#issuecomment-289035698.

> What's the point on having a preferred port if it's not guaranteed? I'm interested in your use-case.

Sure, having one preferred port is reasonable, but having an array seems pretty random?

**Comment by AxelTerizaki** [comment]
My app is trying to be as user-friendly as possible, so I'm trying to see if port 80 is available to start a webserver on it. It might be available, but some OSes don't allow non-admin users to open ports below 1000. So if 80 isn't open, I'd like to try to see if another port I'd like to use (1337) is available and use it. If all else fails, get a random port.

I could always try to call get-port twice, once with port 80 and once with port 1337, too, I guess.

If you consider this is too much hassle, I'll do it my way. Was just an idea of something to add :)
