### ISSUE TITLE
Possible interest in hostenv package

### ISSUE THREAD

**Issue by balupton** [sindresorhus/get-port#22]
Seems this package would go along well with https://github.com/bevry/hostenv for the port and hostname defaults

**Comment by WoZ** [comment]
Why does get-port need it?

**Comment by balupton** [comment]
Would be able to get the port that the host expects right away, rather than trying potentially unused ports. The trying of potentially unused ports can be a fallback if the host did not specify a port.

**Comment by WoZ** [comment]
You are talking about business logic of application. I think that developers should choose such strategy and not a module.

**Comment by sindresorhus** [comment]
I don't think it's a good fit.
