### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by Hongdeshuai** [sindresorhus/get-port#26]
Not responding at all on windows

**Comment by Hongdeshuai** [comment]
return getPort().then(port => {
            console.log("got the port");
            fs.writeFileSync(path.join(util.supportDir(), 'openvpn.port'), port);
            return port;
        }).catch(e => {
            console.log("got the port error here catched",e);
            fs.writeFileSync(path.join(util.supportDir(), 'openvpn.port'), 1194);
            return 1194;
        });

This is my code but I can't see and logs printed.
That means it is not responding at all ?

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.

**Comment by sindresorhus** [comment]
Closing as I don't think this is a problem with `get-port`. Happy to reopen if you submit a failing test.

**Comment by Drulac** [comment]
Same issue, strange because it's was working an hour ago, with the same code :thinking:
