### ISSUE TITLE
conside provide a synchronous mode options ?

### ISSUE THREAD

**Issue by tjx666** [sindresorhus/get-port#41]
Sometime It would be more convenient if the getPort supports synchronous mode.
For example, when I get the get the test config:
```javascript
const _ = require('lodash');
const getPort = require('get-port');
const devConfig = require('./development.config');

exports.server = {
    port: getPort({ sync: true }),
};

exports.security = {
    jwtSecret: 'test_jwt_secret',
    passwordHashSaltRounds: 15,
};

exports.db = {
    dbName: 'coo-test',
};

module.exports = _.merge(devConfig, exports);
```

**Comment by sindresorhus** [comment]
This is not possible. The Node.js API we use to get the port is asynchronous. You can make it synchronous yourself with something like https://github.com/abbr/deasync.
