### ISSUE TITLE
Jest tests time out since 5.1.0

### ISSUE THREAD

**Issue by cegerard** [sindresorhus/get-port#45]
Hi.
I use get-port in my jest test and it works perfectly since the 5.1.0 recent update.

Now my jest tests timeout and jest warns about some open handles from get-port.
Jest warn about this line https://github.com/sindresorhus/get-port/blob/master/index.js#L51 in particular.

My solution to make my test back to work is to downgrade get-port to 5.0.0.

Has anyone encountered this issue ?

**Comment by gzaripov** [comment]
Yes, I did.
Problem is in setInterval inside the library, I think it's the right decision to check that timer wasn't in use, but logic with two generations of times looks overcomplicated for me. On a machine we have 65,535 ports, do we really need two generations? We can add ports to Set `usedPorts` and never use them except when a user specifies that port.

**Comment by dobesv** [comment]
I think this interval thing is a bit weird and should probably be disabled by default.  We're only calling get-port once on startup, we never call it again.  We don't need a timer running forever.

**Comment by sindresorhus** [comment]
Yeah, I think it should use `setTimeout` instead of `setInterval`.
