### ISSUE TITLE
Get the port that is not available

### ISSUE THREAD

**Issue by zcmgyu** [sindresorhus/get-port#47]
* Check 4723 in use:
> lsof -n -i4TCP:4723

* Get free port by `get-port`:
After 1 minute, i run below code.

```
const getPort = require('get-port');

(async () => {
  console.log('port 1 -> ', await getPort({ port: 4723 }));

  setTimeout(async () => {
    console.log('port 2 -> ', await getPort({ port: 4723 }));
  }, 2000);
})();

```

> port 1 ->  4723
> port 2 ->  50129

My PC is using 4723 port, but get-port still gives me 4723 port.

<img width="567" alt="Screen Shot 2020-03-03 at 1 41 36" src="https://user-images.githubusercontent.com/13638569/75698158-91ba4980-5cf1-11ea-979a-cd5e1bc05287.png">

PS: I've tried some other library like `portfinder` and it works as expected.

**Comment by sindresorhus** [comment]
This should be fixed in the latest version: https://github.com/sindresorhus/get-port/releases/tag/v6.0.0
