### ISSUE TITLE
Feature request: Available port for any localhost host (localhost, 0.0.0.0, 127.0.0.1)

### ISSUE THREAD

**Issue by dylang** [sindresorhus/get-port#48]
If `server.listen` is used with a `host`, then `get-port` only returns the correct result if the _same_ `host` value is provided.

```ts
// Some other project running on your machine:
server.listen(3000, 'localhost', cb);
```

This works, because we put in the host `localhost`, matching above:
```ts
// Your project:
await getPort({ port: 3000, host: 'localhost' }) 
// => Random port that is not bound to localhost, good!
```

*However, when you don't know what host was used in the other project, or what host will be used in yours, you could be in trouble:*

```ts
// Some other project running on your machine:
server.listen(3000, 'localhost', cb);

// Your project does one of these:

await getPort({ port: 3000 }) 
// => 3000...

await getPort({ port: 3000, host: '0.0.0.0' }) 
// => 3000...

await getPort({ port: 3000, host: '127.0.0.1' }) 
// => 3000...

await getPort({ port: 3000, host: '::' }) 
// => 3000...
```

If that 3000 port is then used later in your code with `localhost`, it will fail.

This might be a deficiency or feature in `libev`, or I'm not understanding how port binding works when the host is provided. 

## Workaround 1

Always use the same host when creating your server as used when running `get-port`. _I'm finding that to not always be feasible._

## Workaround 2

```ts
Math.max(
  await getPort({ port: 3000, host: 'localhost' }),
  await getPort({ port: 3000, host: '0.0.0.0' })
);
// => Will always be a random port, even if 3000 is available, 
// because `lockedPorts` ignores the `host`, so one of the two 
// getPort calls will think 3000 is already locked and return a random port.
```

## Potential solution?

Maybe a possible workaround is to allow for passing in an array of `hosts`, or an option to check all `localhost` variants?

**Comment by sindresorhus** [comment]
See my comment in https://github.com/sindresorhus/get-port/issues/31#issuecomment-596407350. I think we indeed should *just work* by default.
