### ISSUE TITLE
Feature Request: function to clear the ports cache

### ISSUE THREAD

**Issue by hasezoey** [sindresorhus/get-port#57]
## Description

I would like to request a function where when called the `lockedPorts` reset (both `old` and `young`)
or simply expose that object with `exports` so it can manually be cleared

**Comment by sindresorhus** [comment]
How would you use it? What problems would it solve?

**Comment by hasezoey** [comment]
my use case is to use that function at least in tests instead of having to wait full 30s (double 15s, to be sure), because from the nodejs process we use `get-port` to find a free port, and spawn another process that will use it (non-nodejs), and then we need to stop it and restart (to test start-stop-start), and in between we use `get-port` to test if the port is used up again - but on the second start it gives a different port than the requested (because the used one is still in one of the caches, the start-stop-start would be within less than 15s)

yes we could make it so that the port will not be checked if it is free, but that would kinda go against having `get-port` at all

**Comment by sindresorhus** [comment]
Your use-case is a bit obscure and outside of the intended scope of this package, but I'm not against some kind of method to clear the cache, as long as its use-case is clearly documented.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/get-port/commit/d4fb7f83572bddec350a8ebe4eb6a3902e2795f7
