### ISSUE TITLE
(0 , _getPort.portNumbers) is not a function

### ISSUE THREAD

**Issue by YiyuanYin** [sindresorhus/get-port#61]
When I run the below code in an Electron app
```
import getPort, { portNumbers } from 'get-port';
const port = (await getPort({ port: portNumbers(7092, 65535) })).toString();
```
I encountered the problem ``(0 , _getPort.portNumbers) is not a function`` 
![9A724661-9408-41d0-9251-1C8AB82DA8A2](https://user-images.githubusercontent.com/9218146/152933069-d49fcd6b-d044-4e4b-acfb-20f715bf83a5.png)

**Comment by sindresorhus** [comment]
This is a problem with the tool/bundler you use, not this package.
