### ISSUE TITLE
Possible portNumbers argument validation bug?

### ISSUE THREAD

**Issue by jonahsnider** [sindresorhus/get-port#62]
https://github.com/sindresorhus/get-port/blob/50e24f66bc142f5197d74f180a9717425bd18133/index.js#L163-L165

Is this `+ 1` logic correct?

If you run this snippet:
```js
import { portNumbers } from 'get-port';

console.log([...portNumbers(65535, 65536)]);
```

You get the output

```js
[ 65535, 65536 ]
```

The maximum port number should be 65,535 but the argument validation seems to allow the value `65536` to be returned.

If this is a bug I'd be happy to PR it.

**Comment by sindresorhus** [comment]
@mastrzyz

**Comment by mastrzyz** [comment]
Interesting, this does look like a bug but , I'd like some more context @sindresorhus , previously the code was : 


```js
	if (to < 1024 || to > 65_536) {
		throw new RangeError('`to` must be between 1024 and 65536');
	}
```

My change https://github.com/sindresorhus/get-port/commit/d03c07b95d56c441df5de4670bd0951b4999dbd9 , changed it to : 


```js
       const maxPort = 65_535;
	if (to < minPort || to > maxPort + 1) {
		throw new RangeError(`'to' must be between ${minPort} and ${maxPort + 1}`);
	}
```

So its effectively the same code as before, was it always a bug here?

**Comment by sindresorhus** [comment]
> was it always a bug here?

Seems so.
