### ISSUE TITLE
Portnumber Range Doesnot support in ServerSide

### ISSUE THREAD

**Issue by Sukumaran001** [sindresorhus/get-port#67]
**I'm trying to use the server with multiple ports and dynamic response to get the port number within the range of port numbers
but they didn't support it on the server side.**

_get-port version->6.1.2_

```
const getPort = require('get-port');
const {portNumbers} = require('portNumbers')
async ()=>{
    console.log(await getPort({port: portNumbers(5000, 6000)}));
}
```
I'm trying on 

> _import getPort, {portNumbers} from 'get-port';_

but the _import module_ doesn't support on nodejs server, the only use of _require method_

Does anyone Have an idea?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
