### ISSUE TITLE
Node defaults to ipv6 for port resolution

### ISSUE THREAD

**Issue by arcticShadow** [sindresorhus/get-port#8]
We noticed that get-port is defaulting to ipv6 for port resolution, which is giving false positives. i.e. given a default port, it comes back as available, where it is actually not available. 

We will add more info to this issue shortly - Right now, we need an issue link for tracking purposes.

**Comment by muntact** [comment]
Specifically the odd behaviour that we are seeing is that get-port by default checks for an available port using the IPV6 interface `::` so when we check the desired port is available it returns true even if it is blocked for IPV4, however when we tell our server to listen on a port that we expect to be unblocked we get the `EADDRINUSE` error.

There appears to be a slew of somewhat related issues people have raised in the past against node.js where IPV6 vs IPV4 has tripped them up:
https://github.com/nodejs/node-v0.x-archive/issues/14575
https://github.com/nodejs/node-v0.x-archive/issues/9195
https://github.com/nodejs/node-v0.x-archive/issues/9290
https://github.com/restify/node-restify/issues/751

Currently we're resolving this by inlining the get-port code with the expected host that we are binding to:

```const getPort = preferredPort => new Promise((resolve, reject) => {
  const server = net.createServer();
  server.unref();
  server.on('error', reject);

  // explicitly set the host we expect to use for our http server (localhost)
  server.listen({ port: preferredPort, host: '127.0.0.1' }, () => {
    const port = server.address().port;
    server.close(() => {
      resolve(port);
    });
  });
});

const safeGetPort = preferredPort =>
  (preferredPort ? getPort(preferredPort).catch(() => getPort(0)) : getPort(0));

....
// binding the server later:
http.createServer(server).listen({
  port: PREFERRED_PORT,
  host: '127.0.0.1',
}, () => {
  console.log(`server started at: 127.0.0.1:${PREFERRED_PORT}`);
});
 ```

**Comment by muntact** [comment]
Would it be worth adding some configurability to the module wrt the host value used?

a: Pass a host arg verbatim - falling through to undefined: 

```
const getPort = (port, host) => new Promise((resolve, reject) => {
       ...
	server.listen({port, host}, () => {});
});
```

b: Similar to above but have a useIPV6 arg instead of host? - feels like this could be restrictive...

```
const getPort = (port, useIPV6) => new Promise((resolve, reject) => {
	// use localhost addresses?
	const host = useIpV6 ? '::1' : '127.0.0.1';
});
```

c: use a flag to indicate checking both? though this feels almost counter to a single purpose module... i guess if get-port was changed to take a host arg it could be re-used in another module to build this same functionality / allow people to internalize their usage.  

```
const getPortOnHost = (port, host) => new Promise((resolve, reject) => {
	const server = net.createServer();

	server.unref();
	server.on('error', reject);

	server.listen({port, host}, () => {
		const port = server.address().port;
		server.close(() => {
			resolve(port);
		});
	});
});

const getPort = (port, checkBoth) => new Promise((resolve, reject) => {
	const checkChain = getPortOnHost(port, '::1');

	if (checkBoth) {
		checkChain.then(getPortOnHost(port, '127.0.0.1'));
	}

	return checkChain;
});
```

or none of the above :)

**Comment by rtsao** [comment]
According to the [latest Node docs](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback):

`server.listen([port][, host][, backlog][, callback])`

> **If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available**, or the unspecified IPv4 address (0.0.0.0) otherwise.

**Comment by arcticShadow** [comment]
We've seen that documentation. The Problem comes when you are explicitly trying to find a port for ipv4 because for whatever reason you want to bind to ipv4.

**Comment by satazor** [comment]
@sindresorhus are you willing to accept an option for this? If yes, shall we accept the host on the second arg?

**Comment by sindresorhus** [comment]
@satazor Yes, I guess that would be the best solution.

**Comment by acostalima** [comment]
@sindresorhus I've just submitted a PR to address this issue.
